In [2]:
import matplotlib.pyplot as plt
import numpy as np
import open3d as o3d
import io
import cv2
import json

In [2]:
img = cv2.imread('data/depth0177.png', -1)

In [3]:
with open('data/mkv_meta.json') as f:
    intrinsic_params = json.load(f)

In [4]:
camera_intrinsic_params = {}
tmp = intrinsic_params['depth_intrinsics'].copy()
tmp.update(intrinsic_params['depth_resolution'].copy())
camera_intrinsic_params['height'] = tmp['h']
camera_intrinsic_params['width'] = tmp['w']
camera_intrinsic_params['fx'] = tmp['fx']
camera_intrinsic_params['fy'] = tmp['fy']
camera_intrinsic_params['cx'] = tmp['cx']
camera_intrinsic_params['cy'] = tmp['cy']

In [5]:
camera_intrinsic_params

{'height': 576,
 'width': 640,
 'fx': 505.05084228515625,
 'fy': 504.9956359863281,
 'cx': 338.0733642578125,
 'cy': 338.06817626953125}

In [6]:
o3d_depth = o3d.geometry.Image(img)
# camera_intrinsic = o3d.camera.PinholeCameraIntrinsic(
#     o3d.camera.PinholeCameraIntrinsicParameters.Kinect2ColorCameraDefault)
# camera_intrinsic = o3d.io.read_pinhole_camera_intrinsic('data/mkv_meta.json')
camera_intrinsic = o3d.camera.PinholeCameraIntrinsic(**camera_intrinsic_params)

In [7]:
np.unique(np.asarray(o3d_depth))

array([   0,  653,  701, ..., 4355, 4361, 5855], dtype=uint16)

In [8]:
pcd = o3d.geometry.PointCloud.create_from_depth_image(o3d_depth, camera_intrinsic)

In [9]:
pcd

PointCloud with 272925 points.

In [10]:
print(np.asarray(pcd.points))

[[ 0.25516271 -1.87847029  2.80599999]
 [ 0.27250845 -1.88315641  2.81299996]
 [ 0.3001436  -1.88181761  2.81100011]
 ...
 [ 0.82715549  1.16027223  2.47300005]
 [ 0.83036972  1.15792629  2.46799994]
 [ 0.83457954  1.15698801  2.46600008]]


In [11]:
o3d.io.write_point_cloud('data/depth0177.ply', pcd, print_progress=True)

True

In [15]:
pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])

PointCloud with 272925 points.

In [ ]:
o3d.visualization.draw_geometries([pcd])

In [3]:
pcd = o3d.io.read_point_cloud('data/depth0177.ply')